### ISSUE TITLE
Lab doesn't open via Learn IDE 3

### ISSUE THREAD

**Issue by derrickbozich** [learn-co-curriculum/redux-thunk-lab#13] opened 2018-11-04 23:47 UTC
This is a copy/paste of what I get in the terminal when I try to open the lab through Learn IDE 3:

learn open redux-thunk-lab-cb-000
Looking for lesson...
/usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/lessons/ios_lesson.rb:6:in `detect': undefined method `any?' for false:FalseClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:20:in `block in classify'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `find'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/lessons.rb:19:in `classify'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/opener.rb:36:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/lib/learn_open/opener.rb:11:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-open-1.2.22/bin/learn-open:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-open:23:in `<main>'

**Comment by maxwellbenton** [comment] 2019-10-03 18:25
Hi @derrickbozich,

Thank you for providing this feedback. I was unable to replicate this issue, but we've recently updated this lab and confirmed that it is currently working. As it looks like there is no current problem, I am going to close this issue.

We apologize for any frustration this issue may have caused. Thank you for contributing to this lesson!

**Closed as completed by maxwellbenton** 2019-10-03 18:25 UTC
